#!/usr/bin/env php
<?php
define('DS', DIRECTORY_SEPARATOR);
define('ROOT', dirname(__FILE__) . DS);
define('APP_PATH', ROOT . 'application' . DS);
require_once APP_PATH . 'Config.php';

$usuario=DB_USER;
$password=DB_PASS;

try{

    $conn = new PDO('mysql:host=localhost;dbname=myfile', $usuario, $password);

    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

}catch(PDOException $e){

    echo "ERROR: " . $e->getMessage();

}
	
?>
